# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='----', max_length=50)),
                ('desg', models.CharField(choices=[('Worker', 'Worker'), ('Manager', 'Manager'), ('Board', 'Board')], default='Worker', max_length=50)),
                ('qual', models.CharField(max_length=1000)),
                ('experience', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('orderby', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('delivery_date', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PostPay', 'PostPay'), ('HalfPay', 'HalfPay'), ('PostPay', 'PostPay')], default='PostPay', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='products')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Dealer')),
            ],
        ),
    ]
