# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentmode',
            field=models.CharField(choices=[('PostPay', 'PostPay'), ('HalfPay', 'HalfPay'), ('PostPay', 'PostPay')], default='PostPay', max_length=10),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='website',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Received', max_length=50),
        ),
    ]
