# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180405_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.FileField(default='/media/background3.jpg', upload_to='employees'),
        ),
    ]
