# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180406_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(upload_to='employees'),
        ),
    ]
